version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: be_postgres
    restart: always
    environment:
      POSTGRES_DB: university_cms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d university_cms"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: be_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: be_minio
    restart: always
    ports:
      - "9000:9000"   # API
      - "9091:9001"   # Web Console (Tránh trùng port 9001 của Portainer)
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  omniroute:
    image: litellm/litellm:main-latest
    container_name: omniroute_gateway
    restart: always
    ports:
      - "8090:4000"
    volumes:
      - ./omniroute/config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--detailed_debug" ]
    environment:
      - LITELLM_MASTER_KEY=sk-omniroute-secret-key

volumes:
  postgres_data:
  redis_data:
  minio_data:
