"""remove_is_featured_from_articles

Revision ID: 06ae7a11ff59
Revises: 30ffce7d83e2
Create Date: 2026-07-04 13:23:00.115735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae7a11ff59'
down_revision: Union[str, None] = '30ffce7d83e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_featured_pinned', table_name='articles')
    op.drop_column('articles', 'is_featured')
    op.create_index('idx_articles_pinned_status', 'articles', ['status', 'is_pinned', 'publish_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_articles_pinned_status', table_name='articles')
    op.add_column('articles', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('idx_articles_featured_pinned', 'articles', ['status', 'is_pinned', 'is_featured', 'publish_at'], unique=False)
    # ### end Alembic commands ###
