"""create_articles_table

Revision ID: 12e43ba5d14e
Revises: baff9814ec93
Create Date: 2026-06-29 17:20:39.075383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e43ba5d14e'
down_revision: Union[str, None] = 'baff9814ec93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create article_status enum type in postgres
    article_status = sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='article_status')
    article_status.create(op.get_bind(), checkfirst=True)

    op.add_column('articles', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('author_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('articles', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('articles', sa.Column('excerpt', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('articles', sa.Column('thumbnail_object_key', sa.String(length=512), nullable=True))
    op.add_column('articles', sa.Column('cover_object_key', sa.String(length=512), nullable=True))
    op.add_column('articles', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='article_status'), nullable=False))
    op.add_column('articles', sa.Column('is_featured', sa.Boolean(), nullable=False))
    op.add_column('articles', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('articles', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('canonical_url', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('robots', sa.String(length=50), nullable=True))
    op.add_column('articles', sa.Column('og_title', sa.String(length=255), nullable=True))
    op.add_column('articles', sa.Column('og_description', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('og_image', sa.String(length=512), nullable=True))
    op.add_column('articles', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('reading_time', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_articles_category_query', 'articles', ['category_id', 'status', 'publish_at'], unique=False)
    op.create_index('idx_articles_featured_pinned', 'articles', ['status', 'is_pinned', 'is_featured', 'publish_at'], unique=False)
    op.create_index('idx_articles_list_query', 'articles', ['status', 'publish_at'], unique=False)
    op.create_index(op.f('ix_articles_author_id'), 'articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_articles_category_id'), 'articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_articles_deleted_at'), 'articles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_articles_publish_at'), 'articles', ['publish_at'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.drop_constraint('articles_seo_og_image_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.drop_column('articles', 'seo_robots')
    op.drop_column('articles', 'seo_og_image_id')
    op.drop_column('articles', 'seo_keywords')
    op.drop_column('articles', 'seo_canonical')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('seo_canonical', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('seo_keywords', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('seo_og_image_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('seo_robots', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_seo_og_image_id_fkey', 'articles', 'media_items', ['seo_og_image_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index(op.f('ix_articles_publish_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_deleted_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_category_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_author_id'), table_name='articles')
    op.drop_index('idx_articles_list_query', table_name='articles')
    op.drop_index('idx_articles_featured_pinned', table_name='articles')
    op.drop_index('idx_articles_category_query', table_name='articles')
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'last_edited_at')
    op.drop_column('articles', 'expire_at')
    op.drop_column('articles', 'published_at')
    op.drop_column('articles', 'publish_at')
    op.drop_column('articles', 'reading_time')
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'view_count')
    op.drop_column('articles', 'og_image')
    op.drop_column('articles', 'og_description')
    op.drop_column('articles', 'og_title')
    op.drop_column('articles', 'robots')
    op.drop_column('articles', 'canonical_url')
    op.drop_column('articles', 'sort_order')
    op.drop_column('articles', 'is_pinned')
    op.drop_column('articles', 'is_featured')
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'cover_object_key')
    op.drop_column('articles', 'thumbnail_object_key')
    op.drop_column('articles', 'content')
    op.drop_column('articles', 'excerpt')
    op.drop_column('articles', 'slug')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'author_id')
    op.drop_column('articles', 'category_id')
    
    # Drop article_status enum type in postgres
    article_status = sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='article_status')
    article_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
