"""add ai_summary_enabled to article

Revision ID: 19e4fc54f4cb
Revises: 397873b33a3c
Create Date: 2026-06-29 11:10:13.819175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e4fc54f4cb'
down_revision: Union[str, None] = '397873b33a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_revisions', sa.Column('ai_summary_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('articles', sa.Column('ai_summary_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ai_summary_enabled')
    op.drop_column('article_revisions', 'ai_summary_enabled')
    # ### end Alembic commands ###
