"""add_is_draft_to_articles

Revision ID: 1d437ef54d61
Revises: 3d41552e838e
Create Date: 2026-06-29 20:38:20.398881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d437ef54d61'
down_revision: Union[str, None] = '3d41552e838e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_draft', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_articles_is_draft'), 'articles', ['is_draft'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_is_draft'), table_name='articles')
    op.drop_column('articles', 'is_draft')
    # ### end Alembic commands ###
