"""create_consultations_table

Revision ID: 29bbea4da158
Revises: 88cecd01e508
Create Date: 2026-07-06 20:34:12.213407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bbea4da158'
down_revision: Union[str, None] = '88cecd01e508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', name='consultation_status'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_assigned_to'), 'consultations', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_consultations_phone'), 'consultations', ['phone'], unique=False)
    op.create_index(op.f('ix_consultations_request_code'), 'consultations', ['request_code'], unique=True)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_request_code'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_phone'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_assigned_to'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
