"""Add article revisions and versions for Phase 5

Revision ID: 2ae982c0285e
Revises: d636513aca8a
Create Date: 2026-06-29 00:46:53.522646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ae982c0285e'
down_revision: Union[str, None] = 'd636513aca8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    # Create RevisionStatus ENUM
    if op.get_context().dialect.name == 'postgresql':
        revision_status_enum = postgresql.ENUM('DRAFT', 'PENDING', 'REJECTED', 'MERGED', name='revision_status_enum')
        revision_status_enum.create(op.get_bind(), checkfirst=True)

        op.execute("ALTER TYPE workflow_action_enum ADD VALUE IF NOT EXISTS 'CREATE_REVISION'")
        op.execute("ALTER TYPE workflow_action_enum ADD VALUE IF NOT EXISTS 'UPDATE_REVISION'")
        op.execute("ALTER TYPE workflow_action_enum ADD VALUE IF NOT EXISTS 'DELETE_REVISION'")
        op.execute("ALTER TYPE workflow_action_enum ADD VALUE IF NOT EXISTS 'MERGE_REVISION'")
        op.execute("ALTER TYPE workflow_action_enum ADD VALUE IF NOT EXISTS 'ROLLBACK'")
        
    op.execute("TRUNCATE TABLE article_revisions CASCADE")
    op.create_table('article_versions',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_json', sa.JSON().with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_versions_article_id'), 'article_versions', ['article_id'], unique=False)
    op.create_table('article_revision_relations',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('target_article_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['article_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_revision_relations_revision_id'), 'article_revision_relations', ['revision_id'], unique=False)
    op.create_index(op.f('ix_article_revision_relations_target_article_id'), 'article_revision_relations', ['target_article_id'], unique=False)
    op.create_table('article_revision_tags',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['article_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_revision_tags_revision_id'), 'article_revision_tags', ['revision_id'], unique=False)
    op.create_index(op.f('ix_article_revision_tags_tag_id'), 'article_revision_tags', ['tag_id'], unique=False)
    op.drop_table('article_related')
    op.drop_index('ix_article_daily_stats_article_id', table_name='article_daily_stats')
    op.drop_index('ix_article_daily_stats_date', table_name='article_daily_stats')
    op.drop_table('article_daily_stats')
    op.drop_table('article_bookmarks')
    op.drop_table('article_stats')
    op.drop_table('article_series')
    op.drop_index('ix_series_slug', table_name='series')
    op.drop_table('series')
    op.drop_index('ix_article_media_article_id', table_name='article_media')
    op.drop_table('article_media')
    op.drop_index('ix_article_ai_jobs_article_id', table_name='article_ai_jobs')
    op.drop_table('article_ai_jobs')
    op.drop_index('ix_comments_article_id', table_name='comments')
    op.drop_index('ix_comments_parent_id', table_name='comments')
    op.drop_index('ix_comments_status', table_name='comments')
    op.drop_table('comments')
    op.add_column('article_revisions', sa.Column('revision_no', sa.Integer(), nullable=False))
    op.add_column('article_revisions', sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'REJECTED', 'MERGED', name='revision_status_enum'), nullable=False))
    op.add_column('article_revisions', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('article_revisions', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('article_revisions', sa.Column('category_id', sa.UUID(), nullable=True))
    op.add_column('article_revisions', sa.Column('banner_image_id', sa.UUID(), nullable=True))
    op.add_column('article_revisions', sa.Column('author_id', sa.UUID(), nullable=False))
    op.add_column('article_revisions', sa.Column('locked_by', sa.UUID(), nullable=True))
    op.add_column('article_revisions', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('article_revisions', sa.Column('seo_canonical', sa.String(length=255), nullable=True))
    op.add_column('article_revisions', sa.Column('seo_robots', sa.String(length=50), nullable=True))
    op.add_column('article_revisions', sa.Column('seo_og_image_id', sa.UUID(), nullable=True))
    op.alter_column('article_revisions', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_article_revisions_author_id'), 'article_revisions', ['author_id'], unique=False)
    op.create_index(op.f('ix_article_revisions_category_id'), 'article_revisions', ['category_id'], unique=False)
    op.create_index(op.f('ix_article_revisions_slug'), 'article_revisions', ['slug'], unique=False)
    op.create_index(op.f('ix_article_revisions_status'), 'article_revisions', ['status'], unique=False)
    op.drop_constraint('article_revisions_created_by_fkey', 'article_revisions', type_='foreignkey')
    op.create_foreign_key(None, 'article_revisions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'article_revisions', 'media_items', ['seo_og_image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'article_revisions', 'users', ['author_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'article_revisions', 'users', ['locked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'article_revisions', 'media_items', ['banner_image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('article_revisions', 'created_by')
    op.drop_column('article_revisions', 'is_draft')
    op.drop_column('article_revisions', 'save_type')
    op.drop_column('article_revisions', 'summary')
    op.drop_column('article_revisions', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_revisions', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('article_revisions', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('article_revisions', sa.Column('save_type', sa.VARCHAR(length=20), server_default=sa.text("'MANUAL'::character varying"), autoincrement=False, nullable=False))
    op.add_column('article_revisions', sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('article_revisions', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article_revisions', type_='foreignkey')
    op.drop_constraint(None, 'article_revisions', type_='foreignkey')
    op.drop_constraint(None, 'article_revisions', type_='foreignkey')
    op.drop_constraint(None, 'article_revisions', type_='foreignkey')
    op.drop_constraint(None, 'article_revisions', type_='foreignkey')
    op.create_foreign_key('article_revisions_created_by_fkey', 'article_revisions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_article_revisions_status'), table_name='article_revisions')
    op.drop_index(op.f('ix_article_revisions_slug'), table_name='article_revisions')
    op.drop_index(op.f('ix_article_revisions_category_id'), table_name='article_revisions')
    op.drop_index(op.f('ix_article_revisions_author_id'), table_name='article_revisions')
    op.alter_column('article_revisions', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('article_revisions', 'seo_og_image_id')
    op.drop_column('article_revisions', 'seo_robots')
    op.drop_column('article_revisions', 'seo_canonical')
    op.drop_column('article_revisions', 'locked_at')
    op.drop_column('article_revisions', 'locked_by')
    op.drop_column('article_revisions', 'author_id')
    op.drop_column('article_revisions', 'banner_image_id')
    op.drop_column('article_revisions', 'category_id')
    op.drop_column('article_revisions', 'short_description')
    op.drop_column('article_revisions', 'slug')
    op.drop_column('article_revisions', 'status')
    op.drop_column('article_revisions', 'revision_no')
    op.create_table('comments',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='comments_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name='comments_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    op.create_index('ix_comments_status', 'comments', ['status'], unique=False)
    op.create_index('ix_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('ix_comments_article_id', 'comments', ['article_id'], unique=False)
    op.create_table('article_ai_jobs',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_ai_jobs_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_ai_jobs_pkey')
    )
    op.create_index('ix_article_ai_jobs_article_id', 'article_ai_jobs', ['article_id'], unique=False)
    op.create_table('article_media',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_media_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], name='article_media_media_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_media_pkey')
    )
    op.create_index('ix_article_media_article_id', 'article_media', ['article_id'], unique=False)
    op.create_table('series',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='series_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_series_slug', 'series', ['slug'], unique=True)
    op.create_table('article_series',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('series_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_series_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name='article_series_series_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'series_id', name='article_series_pkey')
    )
    op.create_table('article_stats',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shares_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reading_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_read_time_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_stats_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', name='article_stats_pkey')
    )
    op.create_table('article_bookmarks',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_bookmarks_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='article_bookmarks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id', name='article_bookmarks_pkey')
    )
    op.create_table('article_daily_stats',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shares_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_daily_stats_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_daily_stats_pkey')
    )
    op.create_index('ix_article_daily_stats_date', 'article_daily_stats', ['date'], unique=False)
    op.create_index('ix_article_daily_stats_article_id', 'article_daily_stats', ['article_id'], unique=False)
    op.create_table('article_related',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('related_article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_related_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_article_id'], ['articles.id'], name='article_related_related_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'related_article_id', name='article_related_pkey')
    )
    op.drop_index(op.f('ix_article_revision_tags_tag_id'), table_name='article_revision_tags')
    op.drop_index(op.f('ix_article_revision_tags_revision_id'), table_name='article_revision_tags')
    op.drop_table('article_revision_tags')
    op.drop_index(op.f('ix_article_revision_relations_target_article_id'), table_name='article_revision_relations')
    op.drop_index(op.f('ix_article_revision_relations_revision_id'), table_name='article_revision_relations')
    op.drop_table('article_revision_relations')
    op.drop_index(op.f('ix_article_versions_article_id'), table_name='article_versions')
    op.drop_table('article_versions')
    # ### end Alembic commands ###
