"""Add AIVoice and Article tts_voices

Revision ID: 30c5536c32c9
Revises: 7cc94cb35b38
Create Date: 2026-06-29 08:25:02.321801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c5536c32c9'
down_revision: Union[str, None] = '7cc94cb35b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_voices',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('voice_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_voices_provider'), 'ai_voices', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_voices_voice_code'), 'ai_voices', ['voice_code'], unique=True)
    op.add_column('articles', sa.Column('tts_voices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'tts_voices')
    op.drop_index(op.f('ix_ai_voices_voice_code'), table_name='ai_voices')
    op.drop_index(op.f('ix_ai_voices_provider'), table_name='ai_voices')
    op.drop_table('ai_voices')
    # ### end Alembic commands ###
