"""remove_flag_id_from_languages

Revision ID: 30ffce7d83e2
Revises: cf9838565b5e
Create Date: 2026-07-03 23:25:32.319346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ffce7d83e2'
down_revision: Union[str, None] = 'cf9838565b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('languages_flag_id_fkey', 'languages', type_='foreignkey')
    op.drop_column('languages', 'flag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('flag_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('languages_flag_id_fkey', 'languages', 'media_items', ['flag_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
