"""Add preview_url to AIVoice

Revision ID: 397873b33a3c
Revises: 30c5536c32c9
Create Date: 2026-06-29 08:25:50.141489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397873b33a3c'
down_revision: Union[str, None] = '30c5536c32c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_voices', sa.Column('preview_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_voices', 'preview_url')
    # ### end Alembic commands ###
