"""Add ai_jobs and article_audios tables

Revision ID: 3cce82aec0b5
Revises: 2ae982c0285e
Create Date: 2026-06-29 01:12:57.804283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cce82aec0b5'
down_revision: Union[str, None] = '2ae982c0285e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
