"""add_is_weekly_schedule_to_category

Revision ID: 4c91454491cf
Revises: 835afe361e83
Create Date: 2026-06-30 01:47:28.535151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c91454491cf'
down_revision: Union[str, None] = '835afe361e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_weekly_schedule', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_weekly_schedule')
    # ### end Alembic commands ###
