"""rename metadata to meta_data in workflow logs

Revision ID: 580570b2d492
Revises: e20dfb7028b8
Create Date: 2026-06-28 23:33:14.320852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '580570b2d492'
down_revision: Union[str, None] = 'e20dfb7028b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_workflow_logs', 'metadata', new_column_name='meta_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article_workflow_logs', 'meta_data', new_column_name='metadata')
    # ### end Alembic commands ###
