"""add_department_page_fields

Revision ID: 5f24a2e9463a
Revises: 38171cc369dc
Create Date: 2026-07-11 18:44:08.775340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f24a2e9463a'
down_revision: Union[str, None] = '38171cc369dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_translations', sa.Column('mission', sa.Text(), nullable=True))
    op.add_column('department_translations', sa.Column('vision', sa.Text(), nullable=True))
    op.add_column('department_translations', sa.Column('history', sa.Text(), nullable=True))
    op.add_column('department_translations', sa.Column('research_overview', sa.Text(), nullable=True))
    op.add_column('department_translations', sa.Column('seo_title', sa.String(length=255), nullable=True))
    op.add_column('department_translations', sa.Column('seo_description', sa.Text(), nullable=True))
    op.add_column('departments', sa.Column('logo_object_key', sa.String(length=512), nullable=True))
    op.add_column('departments', sa.Column('banner_object_key', sa.String(length=512), nullable=True))
    op.add_column('departments', sa.Column('display_order', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('head_staff_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_departments_head_staff_id', 'departments', 'staffs', ['head_staff_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_departments_head_staff_id', 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_staff_id')
    op.drop_column('departments', 'display_order')
    op.drop_column('departments', 'banner_object_key')
    op.drop_column('departments', 'logo_object_key')
    op.drop_column('department_translations', 'seo_description')
    op.drop_column('department_translations', 'seo_title')
    op.drop_column('department_translations', 'research_overview')
    op.drop_column('department_translations', 'history')
    op.drop_column('department_translations', 'vision')
    op.drop_column('department_translations', 'mission')
    # ### end Alembic commands ###
