"""add_is_locked_to_category

Revision ID: 6714ba60b4d0
Revises: 4c91454491cf
Create Date: 2026-06-30 01:49:35.228911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6714ba60b4d0'
down_revision: Union[str, None] = '4c91454491cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_locked')
    # ### end Alembic commands ###
