"""Replace tts with ai models

Revision ID: 7cc94cb35b38
Revises: 3cce82aec0b5
Create Date: 2026-06-29 01:38:27.376003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc94cb35b38'
down_revision: Union[str, None] = '3cce82aec0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_url', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_target_id'), 'ai_jobs', ['target_id'], unique=False)
    op.create_table('article_audios',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('voice_code', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_audios_article_id'), 'article_audios', ['article_id'], unique=False)
    op.drop_index('ix_article_audio_article_id', table_name='article_audio')
    op.drop_index('ix_article_audio_status', table_name='article_audio')
    op.drop_index('ix_article_audio_voice_id', table_name='article_audio')
    op.drop_table('article_audio')
    op.drop_index('ix_tts_voices_provider', table_name='tts_voices')
    op.drop_index('ix_tts_voices_voice_code', table_name='tts_voices')
    op.drop_table('tts_voices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tts_voices',
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('voice_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sample_audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tts_voices_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tts_voices_voice_code', 'tts_voices', ['voice_code'], unique=True)
    op.create_index('ix_tts_voices_provider', 'tts_voices', ['provider'], unique=False)
    op.create_table('article_audio',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('voice_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('word_timestamps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['tts_voices.id'], name='article_audio_voice_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='article_audio_pkey')
    )
    op.create_index('ix_article_audio_voice_id', 'article_audio', ['voice_id'], unique=False)
    op.create_index('ix_article_audio_status', 'article_audio', ['status'], unique=False)
    op.create_index('ix_article_audio_article_id', 'article_audio', ['article_id'], unique=False)
    op.drop_index(op.f('ix_article_audios_article_id'), table_name='article_audios')
    op.drop_table('article_audios')
    op.drop_index(op.f('ix_ai_jobs_target_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
