"""add_department_to_menu_item_target_type

Revision ID: 835afe361e83
Revises: 90cb7a8e15f1
Create Date: 2026-06-30 01:12:56.856608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835afe361e83'
down_revision: Union[str, None] = '90cb7a8e15f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
