"""create_articles_table

Revision ID: 83dc3707cde2
Revises: 5edd98fd13c3
Create Date: 2026-06-28 23:12:54.689985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83dc3707cde2'
down_revision: Union[str, None] = '5edd98fd13c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    from sqlalchemy.dialects import postgresql
    visibility_enum = postgresql.ENUM('PUBLIC', 'INTERNAL', 'ROLE_BASED', name='visibility_level_enum')
    visibility_enum.create(op.get_bind(), checkfirst=True)
    status_enum = postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', name='article_status_enum')
    status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('articles', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('banner_image_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('visibility', sa.Enum('PUBLIC', 'INTERNAL', 'ROLE_BASED', name='visibility_level_enum'), nullable=False, server_default='PUBLIC'))
    op.alter_column('articles', 'visibility', server_default=None)
    op.add_column('articles', sa.Column('author_id', sa.UUID(), nullable=True))
    op.execute('UPDATE articles SET author_id = (SELECT id FROM users LIMIT 1)')
    op.alter_column('articles', 'author_id', nullable=False)
    op.add_column('articles', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('articles', 'is_pinned', server_default=None)
    
    op.add_column('articles', sa.Column('content_hash', sa.String(length=64), nullable=True))
    
    op.add_column('articles', sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.alter_column('articles', 'version', server_default=None)
    
    op.add_column('articles', sa.Column('locked_by', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('articles', sa.Column('translation_group_id', sa.UUID(), nullable=True))
    
    op.add_column('articles', sa.Column('locale', sa.String(length=10), nullable=False, server_default=sa.text("'vi-VN'")))
    op.alter_column('articles', 'locale', server_default=None)
    
    op.add_column('articles', sa.Column('reading_time', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('articles', 'reading_time', server_default=None)
    
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('articles', 'word_count', server_default=None)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('articles', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.execute("UPDATE articles SET status = 'PENDING' WHERE status NOT IN ('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED')")
    op.alter_column('articles', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', name='article_status_enum'),
               existing_nullable=False,
               postgresql_using="status::article_status_enum")
    op.drop_index('ix_articles_deleted_at', table_name='articles')
    op.create_index(op.f('ix_articles_author_id'), 'articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_articles_translation_group_id'), 'articles', ['translation_group_id'], unique=False)
    op.drop_constraint('articles_category_id_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_updated_by_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_approved_by_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_deleted_by_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_created_by_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_thumbnail_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'media_items', ['banner_image_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'articles', 'users', ['locked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'articles', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'thumbnail_id')
    op.drop_column('articles', 'created_by')
    op.drop_column('articles', 'scheduled_at')
    op.drop_column('articles', 'published_at')
    op.drop_column('articles', 'summary')
    op.drop_column('articles', 'is_breaking')
    op.drop_column('articles', 'updated_by')
    op.drop_column('articles', 'is_sticky')
    op.drop_column('articles', 'approved_by')
    op.drop_column('articles', 'deleted_by')
    op.drop_column('articles', 'allow_comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('allow_comments', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('is_sticky', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('is_breaking', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('articles', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('thumbnail_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_thumbnail_id_fkey', 'articles', 'media_items', ['thumbnail_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('articles_created_by_fkey', 'articles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('articles_deleted_by_fkey', 'articles', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('articles_approved_by_fkey', 'articles', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('articles_updated_by_fkey', 'articles', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('articles_category_id_fkey', 'articles', 'categories', ['category_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_articles_translation_group_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_author_id'), table_name='articles')
    op.create_index('ix_articles_deleted_at', 'articles', ['deleted_at'], unique=False)
    op.alter_column('articles', 'status',
               existing_type=sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', name='article_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('articles', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('articles', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'reading_time')
    op.drop_column('articles', 'locale')
    op.drop_column('articles', 'translation_group_id')
    op.drop_column('articles', 'locked_at')
    op.drop_column('articles', 'locked_by')
    op.drop_column('articles', 'version')
    op.drop_column('articles', 'content_hash')
    op.drop_column('articles', 'is_pinned')
    op.drop_column('articles', 'author_id')
    op.drop_column('articles', 'visibility')
    op.drop_column('articles', 'banner_image_id')
    op.drop_column('articles', 'short_description')

    # ### end Alembic commands ###
