"""create_system_statistics_table

Revision ID: 88cecd01e508
Revises: 06ae7a11ff59
Create Date: 2026-07-04 21:13:50.196115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cecd01e508'
down_revision: Union[str, None] = '06ae7a11ff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_statistics',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_statistics')
    # ### end Alembic commands ###
