"""remove ai settings models

Revision ID: 894c98fd09bb
Revises: d6569ddf450b
Create Date: 2026-06-29 15:48:35.640643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '894c98fd09bb'
down_revision: Union[str, None] = 'd6569ddf450b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_logs_user_id', table_name='ai_usage_logs')
    op.drop_table('ai_usage_logs')
    op.drop_table('ai_settings')
    op.drop_index('ix_ai_model_pricing_model_name', table_name='ai_model_pricing')
    op.drop_index('ix_ai_model_pricing_provider', table_name='ai_model_pricing')
    op.drop_table('ai_model_pricing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_pricing',
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('input_price_per_1m', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('output_price_per_1m', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ai_model_pricing_pkey')
    )
    op.create_index('ix_ai_model_pricing_provider', 'ai_model_pricing', ['provider'], unique=False)
    op.create_index('ix_ai_model_pricing_model_name', 'ai_model_pricing', ['model_name'], unique=True)
    op.create_table('ai_settings',
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timeout', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('monthly_budget_limit', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('50.0000'), autoincrement=False, nullable=False),
    sa.Column('monthly_spent', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0.0000'), autoincrement=False, nullable=False),
    sa.Column('budget_reset_day', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.Column('setting_type', sa.VARCHAR(length=20), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='ai_settings_updated_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ai_settings_pkey')
    )
    op.create_table('ai_usage_logs',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.NUMERIC(precision=12, scale=6), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_usage_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='ai_usage_logs_pkey')
    )
    op.create_index('ix_ai_usage_logs_user_id', 'ai_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
