"""remove_ai_tables

Revision ID: 8cc9ca5bd768
Revises: 95a93c14b149
Create Date: 2026-06-29 16:05:07.371836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc9ca5bd768'
down_revision: Union[str, None] = '95a93c14b149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_jobs_target_id', table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index('ix_article_audios_article_id', table_name='article_audios')
    op.drop_table('article_audios')
    op.drop_index('ix_ai_voices_provider', table_name='ai_voices')
    op.drop_index('ix_ai_voices_voice_code', table_name='ai_voices')
    op.drop_table('ai_voices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_voices',
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('voice_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('preview_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_voices_pkey')
    )
    op.create_index('ix_ai_voices_voice_code', 'ai_voices', ['voice_code'], unique=True)
    op.create_index('ix_ai_voices_provider', 'ai_voices', ['provider'], unique=False)
    op.create_table('article_audios',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('voice_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_audios_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_audios_pkey')
    )
    op.create_index('ix_article_audios_article_id', 'article_audios', ['article_id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['articles.id'], name='ai_jobs_target_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_jobs_pkey')
    )
    op.create_index('ix_ai_jobs_target_id', 'ai_jobs', ['target_id'], unique=False)
    # ### end Alembic commands ###
