"""create_banners_table

Revision ID: 90cb7a8e15f1
Revises: f7fbd5eedc2d
Create Date: 2026-06-30 00:44:01.109643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cb7a8e15f1'
down_revision: Union[str, None] = 'f7fbd5eedc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('desktop_image_object_key', sa.String(length=512), nullable=False),
    sa.Column('mobile_image_object_key', sa.String(length=512), nullable=True),
    sa.Column('link_url', sa.String(length=1000), nullable=True),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Enum('HOME_HERO', 'HOME_POPUP', 'HOME_TOP', 'NEWS_TOP', 'CATEGORY_TOP', 'PAGE_TOP', name='banner_position'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_banner_active', 'banners', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_banner_end', 'banners', ['end_at'], unique=False)
    op.create_index('idx_banner_position', 'banners', ['position'], unique=False)
    op.create_index('idx_banner_sort', 'banners', ['position', 'sort_order'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_banner_start', 'banners', ['start_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_banner_start', table_name='banners')
    op.drop_index('idx_banner_sort', table_name='banners', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_banner_position', table_name='banners')
    op.drop_index('idx_banner_end', table_name='banners')
    op.drop_index('idx_banner_active', table_name='banners', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('banners')
    # ### end Alembic commands ###
