"""create_category_translations_and_drop_legacy_fields

Revision ID: a54da999ea87
Revises: c289ccee0b64
Create Date: 2026-07-01 01:21:31.910315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54da999ea87'
down_revision: Union[str, None] = 'c289ccee0b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_translations',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'language_id', name='uq_category_language_unique'),
    sa.UniqueConstraint('language_id', 'slug', name='uq_language_slug_unique')
    )
    op.create_index(op.f('ix_category_translations_category_id'), 'category_translations', ['category_id'], unique=False)
    op.create_index('ix_category_translations_category_language', 'category_translations', ['category_id', 'language_id'], unique=False)
    op.create_index(op.f('ix_category_translations_language_id'), 'category_translations', ['language_id'], unique=False)
    op.create_index('ix_category_translations_language_slug', 'category_translations', ['language_id', 'slug'], unique=False)
    # Copy toàn bộ dữ liệu hiện có từ các cột cũ của categories sang category_translations cho tiếng Việt 'vi'
    connection = op.get_bind()
    lang_result = connection.execute(
        sa.text("SELECT id FROM languages WHERE code = 'vi'")
    ).fetchone()
    
    if lang_result:
        vi_lang_id = lang_result[0]
        results = connection.execute(
            sa.text("SELECT id, name, slug, description, seo_title, seo_description, created_at, updated_at FROM categories")
        ).fetchall()
        
        import uuid
        for row in results:
            connection.execute(
                sa.text(
                    "INSERT INTO category_translations (id, category_id, language_id, name, slug, description, seo_title, seo_description, created_at, updated_at) "
                    "VALUES (:id, :category_id, :language_id, :name, :slug, :description, :seo_title, :seo_description, :created_at, :updated_at)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "category_id": str(row[0]),
                    "language_id": str(vi_lang_id),
                    "name": row[1],
                    "slug": row[2],
                    "description": row[3],
                    "seo_title": row[4],
                    "seo_description": row[5],
                    "created_at": row[6],
                    "updated_at": row[7]
                }
            )

    op.drop_index('ix_categories_slug', table_name='categories')
    op.drop_constraint('categories_seo_og_image_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'slug')
    op.drop_column('categories', 'name')
    op.drop_column('categories', 'seo_og_image_id')
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'seo_canonical')
    op.drop_column('categories', 'seo_robots')
    op.drop_column('categories', 'seo_description')
    op.drop_column('categories', 'seo_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('seo_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('seo_robots', sa.VARCHAR(length=50), server_default=sa.text("'index, follow'::character varying"), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('seo_canonical', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('seo_og_image_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_seo_og_image_id_fkey', 'categories', 'media_items', ['seo_og_image_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_categories_slug', 'categories', ['slug'], unique=True)
    op.drop_index('ix_category_translations_language_slug', table_name='category_translations')
    op.drop_index(op.f('ix_category_translations_language_id'), table_name='category_translations')
    op.drop_index('ix_category_translations_category_language', table_name='category_translations')
    op.drop_index(op.f('ix_category_translations_category_id'), table_name='category_translations')
    op.drop_table('category_translations')
    # ### end Alembic commands ###
