"""create_tags_table

Revision ID: baff9814ec93
Revises: e16d00a1e979
Create Date: 2026-06-29 17:11:18.937687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baff9814ec93'
down_revision: Union[str, None] = 'e16d00a1e979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_keywords', sa.String(length=255), nullable=True),
    sa.Column('seo_canonical', sa.String(length=255), nullable=True),
    sa.Column('seo_robots', sa.String(length=50), nullable=True),
    sa.Column('seo_og_image_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['seo_og_image_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tags', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('tags', sa.Column('usage_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tags', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tags', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('tags', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tags', 'slug',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_tags_deleted_at'), 'tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tags_is_active'), 'tags', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_is_active'), table_name='tags')
    op.drop_index(op.f('ix_tags_deleted_at'), table_name='tags')
    op.alter_column('tags', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('tags', 'deleted_at')
    op.drop_column('tags', 'is_active')
    op.drop_column('tags', 'sort_order')
    op.drop_column('tags', 'usage_count')
    op.drop_column('tags', 'color')
    op.drop_table('articles')
    # ### end Alembic commands ###
