"""add view_count to article

Revision ID: bb2d4a346093
Revises: 19e4fc54f4cb
Create Date: 2026-06-29 12:13:15.044475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2d4a346093'
down_revision: Union[str, None] = '19e4fc54f4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'view_count')
    # ### end Alembic commands ###
