"""create_languages_table

Revision ID: c289ccee0b64
Revises: 6714ba60b4d0
Create Date: 2026-06-30 22:48:09.224801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c289ccee0b64'
down_revision: Union[str, None] = '6714ba60b4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_deleted_at'), 'languages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_languages_is_active'), 'languages', ['is_active'], unique=False)
    op.create_index(op.f('ix_languages_is_default'), 'languages', ['is_default'], unique=False)
    op.create_index(op.f('ix_languages_sort_order'), 'languages', ['sort_order'], unique=False)
    
    # Seed dữ liệu mặc định
    import uuid
    from datetime import datetime, UTC
    
    language_table = sa.table(
        'languages',
        sa.column('id', sa.UUID),
        sa.column('code', sa.String),
        sa.column('name', sa.String),
        sa.column('native_name', sa.String),
        sa.column('flag_id', sa.UUID),
        sa.column('is_default', sa.Boolean),
        sa.column('is_system', sa.Boolean),
        sa.column('is_active', sa.Boolean),
        sa.column('sort_order', sa.Integer),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True))
    )
    
    op.bulk_insert(
        language_table,
        [
            {
                'id': uuid.uuid4(),
                'code': 'vi',
                'name': 'Vietnamese',
                'native_name': 'Tiếng Việt',
                'flag_id': None,
                'is_default': True,
                'is_system': True,
                'is_active': True,
                'sort_order': 0,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            },
            {
                'id': uuid.uuid4(),
                'code': 'en',
                'name': 'English',
                'native_name': 'English',
                'flag_id': None,
                'is_default': False,
                'is_system': True,
                'is_active': True,
                'sort_order': 1,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            },
            {
                'id': uuid.uuid4(),
                'code': 'lo',
                'name': 'Lao',
                'native_name': 'ພາສາລາວ',
                'flag_id': None,
                'is_default': False,
                'is_system': True,
                'is_active': True,
                'sort_order': 2,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_languages_sort_order'), table_name='languages')
    op.drop_index(op.f('ix_languages_is_default'), table_name='languages')
    op.drop_index(op.f('ix_languages_is_active'), table_name='languages')
    op.drop_index(op.f('ix_languages_deleted_at'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
