"""Add ai request logs table

Revision ID: cf9838565b5e
Revises: 72190d46e1b6
Create Date: 2026-07-02 11:01:43.041201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf9838565b5e'
down_revision: Union[str, None] = '72190d46e1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_request_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_request_logs_model'), 'ai_request_logs', ['model'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_status'), 'ai_request_logs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_request_logs_user_id'), 'ai_request_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_article_translations_article_id'), 'article_translations', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_translations_language_id'), 'article_translations', ['language_id'], unique=False)
    op.drop_column('categories', 'is_locked')
    op.alter_column('department_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('department_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('uidx_department_trans_slug', table_name='department_translations')
    op.drop_index('idx_departments_list', table_name='departments', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('menu_item_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('menu_item_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_menu_item_translations_language_id'), 'menu_item_translations', ['language_id'], unique=False)
    op.create_index(op.f('ix_menu_item_translations_menu_item_id'), 'menu_item_translations', ['menu_item_id'], unique=False)
    op.alter_column('position_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('position_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('idx_positions_list', table_name='positions', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('staff_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('staff_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('idx_staff_active', table_name='staffs', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_staff_department', table_name='staffs', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_staff_name', table_name='staffs')
    op.drop_index('idx_staff_position', table_name='staffs', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('uidx_staff_slug', table_name='staffs', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_tag_translations_language_id'), 'tag_translations', ['language_id'], unique=False)
    op.create_index(op.f('ix_tag_translations_tag_id'), 'tag_translations', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_translations_tag_id'), table_name='tag_translations')
    op.drop_index(op.f('ix_tag_translations_language_id'), table_name='tag_translations')
    op.create_index('uidx_staff_slug', 'staffs', ['slug'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_staff_position', 'staffs', ['position_id', 'is_active', 'sort_order'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_staff_name', 'staffs', ['full_name'], unique=False)
    op.create_index('idx_staff_department', 'staffs', ['department_id', 'is_active', 'sort_order'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_staff_active', 'staffs', ['is_active'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('staff_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('staff_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('idx_positions_list', 'positions', ['is_active', 'sort_order'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('position_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('position_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_menu_item_translations_menu_item_id'), table_name='menu_item_translations')
    op.drop_index(op.f('ix_menu_item_translations_language_id'), table_name='menu_item_translations')
    op.alter_column('menu_item_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('menu_item_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index('idx_departments_list', 'departments', ['is_active', 'sort_order'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('uidx_department_trans_slug', 'department_translations', ['slug'], unique=True)
    op.alter_column('department_translations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('department_translations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('categories', sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_article_translations_language_id'), table_name='article_translations')
    op.drop_index(op.f('ix_article_translations_article_id'), table_name='article_translations')
    op.drop_index(op.f('ix_ai_request_logs_user_id'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_status'), table_name='ai_request_logs')
    op.drop_index(op.f('ix_ai_request_logs_model'), table_name='ai_request_logs')
    op.drop_table('ai_request_logs')
    # ### end Alembic commands ###
