"""Add Tag, ArticleRelation and Expiry

Revision ID: d636513aca8a
Revises: 3fa92530ace4
Create Date: 2026-06-29 00:18:40.539956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd636513aca8a'
down_revision: Union[str, None] = '3fa92530ace4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)

    op.create_table('article_tags',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_tags_article_id'), 'article_tags', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tags_tag_id'), 'article_tags', ['tag_id'], unique=False)

    op.create_table('article_relations',
    sa.Column('source_article_id', sa.UUID(), nullable=False),
    sa.Column('target_article_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_relations_source_article_id'), 'article_relations', ['source_article_id'], unique=False)
    op.create_index(op.f('ix_article_relations_target_article_id'), 'article_relations', ['target_article_id'], unique=False)

    op.add_column('articles', sa.Column('scheduled_unpublish_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'scheduled_unpublish_at')
    
    op.drop_index(op.f('ix_article_relations_target_article_id'), table_name='article_relations')
    op.drop_index(op.f('ix_article_relations_source_article_id'), table_name='article_relations')
    op.drop_table('article_relations')

    op.drop_index(op.f('ix_article_tags_tag_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_article_id'), table_name='article_tags')
    op.drop_table('article_tags')

    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
