"""remove_rag_and_revisions

Revision ID: d6569ddf450b
Revises: b220913c43a6
Create Date: 2026-06-29 13:51:04.502639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6569ddf450b'
down_revision: Union[str, None] = 'b220913c43a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_revision_relations_revision_id', table_name='article_revision_relations')
    op.drop_index('ix_article_revision_relations_target_article_id', table_name='article_revision_relations')
    op.drop_table('article_revision_relations')
    op.drop_index('ix_article_revision_tags_revision_id', table_name='article_revision_tags')
    op.drop_index('ix_article_revision_tags_tag_id', table_name='article_revision_tags')
    op.drop_table('article_revision_tags')
    op.drop_index('ix_article_versions_article_id', table_name='article_versions')
    op.drop_table('article_versions')
    op.drop_table('knowledge_communities')
    op.drop_index('ix_knowledge_citations_chunk_id', table_name='knowledge_citations')
    op.drop_index('ix_knowledge_citations_entity_id', table_name='knowledge_citations')
    op.drop_index('ix_knowledge_citations_relationship_id', table_name='knowledge_citations')
    op.drop_table('knowledge_citations')
    op.drop_index('ix_knowledge_relationships_source_entity_id', table_name='knowledge_relationships')
    op.drop_index('ix_knowledge_relationships_target_entity_id', table_name='knowledge_relationships')
    op.drop_table('knowledge_relationships')
    op.drop_index('ix_article_workflow_logs_action', table_name='article_workflow_logs')
    op.drop_index('ix_article_workflow_logs_action_by', table_name='article_workflow_logs')
    op.drop_index('ix_article_workflow_logs_article_id', table_name='article_workflow_logs')
    op.drop_table('article_workflow_logs')
    op.drop_index('ix_article_revisions_article_id', table_name='article_revisions')
    op.drop_index('ix_article_revisions_author_id', table_name='article_revisions')
    op.drop_index('ix_article_revisions_category_id', table_name='article_revisions')
    op.drop_index('ix_article_revisions_slug', table_name='article_revisions')
    op.drop_index('ix_article_revisions_status', table_name='article_revisions')
    op.drop_table('article_revisions')
    op.drop_index('ix_knowledge_chunks_source_id', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_entities_name', table_name='knowledge_entities')
    op.drop_table('knowledge_entities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entities',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='knowledge_entities_pkey'),
    sa.UniqueConstraint('name', 'entity_type', name='unq_entity_name_type'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_knowledge_entities_name', 'knowledge_entities', ['name'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contextual_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('access_roles', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='knowledge_chunks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_knowledge_chunks_source_id', 'knowledge_chunks', ['source_id'], unique=False)
    op.create_table('article_revisions',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('seo_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seo_keywords', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revision_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'REJECTED', 'MERGED', name='revision_status_enum'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('banner_image_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('locked_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('seo_canonical', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('seo_robots', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('seo_og_image_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ai_summary_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_revisions_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='article_revisions_author_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['banner_image_id'], ['media_items.id'], name='article_revisions_banner_image_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='article_revisions_category_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name='article_revisions_locked_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seo_og_image_id'], ['media_items.id'], name='article_revisions_seo_og_image_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='article_revisions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_article_revisions_status', 'article_revisions', ['status'], unique=False)
    op.create_index('ix_article_revisions_slug', 'article_revisions', ['slug'], unique=False)
    op.create_index('ix_article_revisions_category_id', 'article_revisions', ['category_id'], unique=False)
    op.create_index('ix_article_revisions_author_id', 'article_revisions', ['author_id'], unique=False)
    op.create_index('ix_article_revisions_article_id', 'article_revisions', ['article_id'], unique=False)
    op.create_table('article_workflow_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('SUBMIT', 'RESUBMIT', 'APPROVE', 'REJECT', 'PUBLISH', 'SCHEDULE', 'CANCEL_SCHEDULE', 'UNPUBLISH', 'ARCHIVE', 'CREATE_REVISION', 'UPDATE_REVISION', 'DELETE_REVISION', 'MERGE_REVISION', 'ROLLBACK', name='workflow_action_enum'), autoincrement=False, nullable=False),
    sa.Column('from_status', postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', 'REJECTED', name='article_status_enum'), autoincrement=False, nullable=True),
    sa.Column('to_status', postgresql.ENUM('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', 'REJECTED', name='article_status_enum'), autoincrement=False, nullable=True),
    sa.Column('action_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], name='article_workflow_logs_action_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_workflow_logs_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_workflow_logs_pkey')
    )
    op.create_index('ix_article_workflow_logs_article_id', 'article_workflow_logs', ['article_id'], unique=False)
    op.create_index('ix_article_workflow_logs_action_by', 'article_workflow_logs', ['action_by'], unique=False)
    op.create_index('ix_article_workflow_logs_action', 'article_workflow_logs', ['action'], unique=False)
    op.create_table('knowledge_relationships',
    sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['knowledge_entities.id'], name='knowledge_relationships_source_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['knowledge_entities.id'], name='knowledge_relationships_target_entity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='knowledge_relationships_pkey'),
    sa.UniqueConstraint('source_entity_id', 'target_entity_id', 'relation_type', name='unq_relationship'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_knowledge_relationships_target_entity_id', 'knowledge_relationships', ['target_entity_id'], unique=False)
    op.create_index('ix_knowledge_relationships_source_entity_id', 'knowledge_relationships', ['source_entity_id'], unique=False)
    op.create_table('knowledge_citations',
    sa.Column('chunk_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('relationship_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('entity_id IS NOT NULL AND relationship_id IS NULL OR entity_id IS NULL AND relationship_id IS NOT NULL', name='chk_citation_target'),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], name='knowledge_citations_chunk_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['knowledge_entities.id'], name='knowledge_citations_entity_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['knowledge_relationships.id'], name='knowledge_citations_relationship_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='knowledge_citations_pkey')
    )
    op.create_index('ix_knowledge_citations_relationship_id', 'knowledge_citations', ['relationship_id'], unique=False)
    op.create_index('ix_knowledge_citations_entity_id', 'knowledge_citations', ['entity_id'], unique=False)
    op.create_index('ix_knowledge_citations_chunk_id', 'knowledge_citations', ['chunk_id'], unique=False)
    op.create_table('knowledge_communities',
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('entity_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='knowledge_communities_pkey')
    )
    op.create_table('article_versions',
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('snapshot_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('snapshot_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('published_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_versions_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name='article_versions_published_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='article_versions_pkey')
    )
    op.create_index('ix_article_versions_article_id', 'article_versions', ['article_id'], unique=False)
    op.create_table('article_revision_tags',
    sa.Column('revision_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['article_revisions.id'], name='article_revision_tags_revision_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='article_revision_tags_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_revision_tags_pkey')
    )
    op.create_index('ix_article_revision_tags_tag_id', 'article_revision_tags', ['tag_id'], unique=False)
    op.create_index('ix_article_revision_tags_revision_id', 'article_revision_tags', ['revision_id'], unique=False)
    op.create_table('article_revision_relations',
    sa.Column('revision_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['article_revisions.id'], name='article_revision_relations_revision_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], name='article_revision_relations_target_article_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_revision_relations_pkey')
    )
    op.create_index('ix_article_revision_relations_target_article_id', 'article_revision_relations', ['target_article_id'], unique=False)
    op.create_index('ix_article_revision_relations_revision_id', 'article_revision_relations', ['revision_id'], unique=False)
    # ### end Alembic commands ###
