"""optimize_article_indexes_and_archived_at

Revision ID: e16d00a1e979
Revises: 8cc9ca5bd768
Create Date: 2026-06-29 16:16:54.763178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16d00a1e979'
down_revision: Union[str, None] = '8cc9ca5bd768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_articles_author_pub_at', 'articles', ['author_id', 'published_at'], unique=False)
    op.create_index('ix_articles_cat_pub_at', 'articles', ['category_id', 'published_at'], unique=False)
    op.create_index('ix_articles_featured_pub_at', 'articles', ['is_featured', 'published_at'], unique=False)
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ix_articles_status_pub_at', 'articles', ['status', 'published_at'], unique=False)
    op.create_index('ix_articles_updated_at', 'articles', ['updated_at'], unique=False)
    op.create_index('ix_articles_view_count', 'articles', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_view_count', table_name='articles')
    op.drop_index('ix_articles_updated_at', table_name='articles')
    op.drop_index('ix_articles_status_pub_at', table_name='articles')
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_index('ix_articles_featured_pub_at', table_name='articles')
    op.drop_index('ix_articles_cat_pub_at', table_name='articles')
    op.drop_index('ix_articles_author_pub_at', table_name='articles')
    op.drop_column('articles', 'archived_at')
    # ### end Alembic commands ###
