"""create_faculty_staff_tables

Revision ID: f7fbd5eedc2d
Revises: 1d437ef54d61
Create Date: 2026-06-29 22:18:06.230284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fbd5eedc2d'
down_revision: Union[str, None] = '1d437ef54d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_object_key', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_departments_list', 'departments', ['is_active', 'sort_order'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index('uidx_departments_slug', 'departments', ['slug'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('positions',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('english_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_list', 'positions', ['is_active', 'sort_order'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_positions_deleted_at'), 'positions', ['deleted_at'], unique=False)
    op.create_index('uidx_positions_name', 'positions', ['name'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('staffs',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('english_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('academic_title', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('avatar_object_key', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_staff_active', 'staffs', ['is_active'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_staff_department', 'staffs', ['department_id', 'is_active', 'sort_order'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index('idx_staff_name', 'staffs', ['full_name'], unique=False)
    op.create_index('idx_staff_position', 'staffs', ['position_id', 'is_active', 'sort_order'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_index(op.f('ix_staffs_deleted_at'), 'staffs', ['deleted_at'], unique=False)
    op.create_index('uidx_staff_slug', 'staffs', ['slug'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uidx_staff_slug', table_name='staffs', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_staffs_deleted_at'), table_name='staffs')
    op.drop_index('idx_staff_position', table_name='staffs', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_staff_name', table_name='staffs')
    op.drop_index('idx_staff_department', table_name='staffs', postgresql_where='deleted_at IS NULL')
    op.drop_index('idx_staff_active', table_name='staffs', postgresql_where='deleted_at IS NULL')
    op.drop_table('staffs')
    op.drop_index('uidx_positions_name', table_name='positions', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_positions_deleted_at'), table_name='positions')
    op.drop_index('idx_positions_list', table_name='positions', postgresql_where='deleted_at IS NULL')
    op.drop_table('positions')
    op.drop_index('uidx_departments_slug', table_name='departments', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_index('idx_departments_list', table_name='departments', postgresql_where='deleted_at IS NULL')
    op.drop_table('departments')
    # ### end Alembic commands ###
